# Generated by Django 6.0.6 on 2026-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_due_date_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
