# Generated by Django 6.0.6 on 2026-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("study", "Study"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
    ]
