# Generated by Django 6.0.6 on 2026-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_task_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodayTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
