# Generated by Django 6.0.6 on 2026-06-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_todaytask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todaytask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
