# Generated by Django 6.0.6 on 2026-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_alter_todaytask_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todaytask",
            name="focus_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
