# Generated by Django 6.0.6 on 2026-06-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_todaytask_focus_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todaytask",
            name="focus_time",
        ),
    ]
