# Generated by Django 6.0.6 on 2026-07-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0008_remove_todaytask_focus_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="todaytask",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
