# Generated by Django 6.0.6 on 2026-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0009_todaytask_reviewed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_focus_review", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
