# Generated by Django 6.0.6 on 2026-07-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0011_todaytaskhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TodayTaskHistory",
        ),
    ]
